### ISSUE TITLE
Elm debugging in browser

### ISSUE THREAD

**Issue by shivanshxyz** [elm-tooling/gsoc-projects#10]
Hey @Razzeee ,
Do we have any existing browser extension for elm debugging? something like  vue.js or react dev tools browser extension. If no, then this can be an interesting idea to work on. I have prior experience in creating chrome extensions so I can submit a proposal if anyone is available for mentoring.

**Comment by mpizenberg** [comment]
This one is fairly used: https://github.com/kraklin/elm-debug-extension

**Comment by shivanshxyz** [comment]
Also not just me, if any other participant feels confident for this project then feel free to work on it as I am working on another proposal and there's only so much one can do in a limited time frame.

**Comment by shivanshxyz** [comment]
> This one is fairly used: https://github.com/kraklin/elm-debug-extension

Oh, nevermind then. Thanks for mentioning

**Comment by mpizenberg** [comment]
It's probably not as developed as the something like debugging extension for react I suppose since react community is huge. That extension is mostly for pretty printing calls to `Debug.log`. Otherwise there is also the official `elm make --debug` option, sometimes called the "time travel debugger".

**Comment by razzeee** [comment]
I'm not sure what we could do here. There have been some tests on actual debugging from vscode, but that's still too early I think. Closing this for now, feel free to reopen.
