### ISSUE TITLE
Proposal for org mode parser

### ISSUE THREAD

**Issue by J0HN50N133** [elm-tooling/gsoc-projects#12]
Hey everyone, I'm Junxian Li,a Sophomore from China and this is my proposal for this year's GSoC.

**Title**: Org mode parser written in pure elm.
**Name**: Junxian Li

**Name in Elm Slack**: JohnsonLee

**Email**: 0xjohnsonlee@gmail

**Summary**:
    The goal of this project is to provide a library that can deal with org-mode file. This enrich the ecosystem of elm.

**How the project will be done:**
    Since org mode is similar to markdown, I think it make sense to start org-mode parser to be equivalent to [elm-markdown parser](https://github.com/dillonkearns/elm-markdown).But org-mode is really rich on features. So to start we should define a set of simple features.

**What will the project focus on:**
    This project will focus on making **extensible and clean** api which support render org-mode file into any type. Once the core is implemented, we could add extensions support for org-mode if time is enough.

**Benefits:**
    With the org-mode parser, we get a way to deal with .org file. We could make static pages with .org file or build interesting apps like online org mode editor.
**Goals:**

- Support Headlines.
- Support markup for rich contents, including **bold**, *italic*, ~~dashed~~, <sub>subscript</sub>.
- Support Table
- Support Blocks
- Support List
- Support basic Hyperlink
- Write some basic test cases
- (Optional)Support TODO items
- (Optional)Support Directive to HTML

### Big-picture

![](https://github.com/JohnsonLee-debug/tuchuang/blob/main/org_mode_parser_big_picture.png?raw=true)

In the first step, the org-mode file would be parsed into a org-mode data tree. Then render function could collect data from the data tree and translate it into a certain component.

#### May 18 - June 8 Community Bonding

Learn more about the community and the mentor and study elm-parser in more depth.

Also, I will communicate with mentors to refine our goal and plan.

#### June 8 - June 16

Define api between the render and parser. This period will focus on big picture and making basic structure. Parsing of headers should be done in this week.

#### June 17 - June 21

Continue working on building data tree.And add html render.

#### June 21 - July 2

This period my university does it's semester evaluations, which usually makes this a very intense period. Therefore I have planned to not do as much work on GSOC for this week. Any time lost will of course be compensated for during the subsequent weeks.

#### July 3 - July 17 (First Evaluation)

The focus in this period would be to get done with the building part of the main features. The remaining time will be used to fix bugs, work on html render, and add extra features. The work will be reviewed by the mentor in the period and any changes required in the project would be scheduled as tasks to complete further.

#### July 18 - July 31

The advice from mentor in the previous phase would be completed during this period. And html render would be completed.

#### August 1 - August 15

Write a documentation for this package and keep fixing bugs for it.

#### August 16 - August 24(Code Submission and Final Evaluation)

Get my final project reviewed by mentor and the community members to get feedback. Also I will write a blog to describe my GSOC experience and what challenges I face while developing the package.

**What's Needed:** Elm, Parsing, Org mode

**Comment by razzeee** [comment]
@akoppela

**Comment by akoppela** [comment]
We had conversation with @JohnsonLee-debug. I think it makes sense to merge our issues.

**Comment by razzeee** [comment]
As far as I understand, this is your complete proposal draft? It's a bit short and not really touching on who you are and how you hope to achieve this. There also is no timeline of your implementation plan.

You might want to check it against https://github.com/elm-tooling/gsoc-projects#proposal-outline again.

**Comment by J0HN50N133** [comment]
> As far as I understand, this is your complete proposal draft? It's a bit short and not really touching on who you are and how you hope to achieve this. There also is no timeline of your implementation plan.
> 
> You might want to check it against https://github.com/elm-tooling/gsoc-projects#proposal-outline again.

Will check it again.
