### ISSUE TITLE
Org mode parser

### ISSUE THREAD

**Issue by akoppela** [elm-tooling/gsoc-projects#4]
Org mode parser

A GNU Emacs major mode for convenient plain text markup — and much more. Org mode is for keeping notes, maintaining to-do lists, planning projects, authoring documents, computational notebooks, literate programming and more — in a fast and effective plain text system.

https://orgmode.org/

What's needed: Elm, Parsing, Org mode
Possible mentor: Anrdey Koppel (akoppela)
Difficulty: Medium

**Comment by razzeee** [comment]
I have no idea, about this, so please bear with me :)

Do you think it's enough work? 

Here's the timeframe for this year: `Starting in 2021, students will be focused on a 175-hour project over a 10-week coding period`

**Comment by akoppela** [comment]
Yes, Org mode specification is large.
